// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD7WKiLuDjIQePi9AsNJ4NiOjiaoTReq4',
    appId: '1:399362348323:web:4066eea059e1e5d3baa896',
    messagingSenderId: '399362348323',
    projectId: 'pravaan-project',
    authDomain: 'pravaan-project.firebaseapp.com',
    storageBucket: 'pravaan-project.firebasestorage.app',
    measurementId: 'G-4128EB82RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7vBn_NlN-cBB3dxLFNCwTd7TTSdUUtV0',
    appId: '1:399362348323:android:0ece305868167b8ebaa896',
    messagingSenderId: '399362348323',
    projectId: 'pravaan-project',
    storageBucket: 'pravaan-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAZRunvsGSL_lXtD51PwjJdouUNQLKlmk',
    appId: '1:399362348323:ios:4ee269741e44cbe2baa896',
    messagingSenderId: '399362348323',
    projectId: 'pravaan-project',
    storageBucket: 'pravaan-project.firebasestorage.app',
    iosBundleId: 'com.pravaan.pravaanFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAZRunvsGSL_lXtD51PwjJdouUNQLKlmk',
    appId: '1:399362348323:ios:4ee269741e44cbe2baa896',
    messagingSenderId: '399362348323',
    projectId: 'pravaan-project',
    storageBucket: 'pravaan-project.firebasestorage.app',
    iosBundleId: 'com.pravaan.pravaanFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD7WKiLuDjIQePi9AsNJ4NiOjiaoTReq4',
    appId: '1:399362348323:web:8147003dc15aeb6fbaa896',
    messagingSenderId: '399362348323',
    projectId: 'pravaan-project',
    authDomain: 'pravaan-project.firebaseapp.com',
    storageBucket: 'pravaan-project.firebasestorage.app',
    measurementId: 'G-LL6WK4H3WS',
  );
}
